Type.create(name: "Family")
Type.create(name: "Friend")
Type.create(name: "Stranger")
Type.create(name: "Coworker")

KindAct.create(description: "On your coffee run today, buy the person behind you in line their coffee")
KindAct.create(description: "Call this person!")
KindAct.create(description: "Send a quick text to check in, express love, and/or share that you're thinking of them")
KindAct.create(description: "See someone's clothes/shoes/hair that you like? Give someone a random compliment!")
KindAct.create(description: "Hold open the door for someone, smile, and make eye contact.")
KindAct.create(description: "Cook them dinner--at your house or theirs!")
KindAct.create(description: "Send them some old school snail mail, like a letter or a postcard!")
KindAct.create(description: "Leave your server a generous tip.")
KindAct.create(description: "Bring some treats into work to share.")
KindAct.create(description: "Send a comment or DM to an influencer you love sharing how they are positively impacting you.")
KindAct.create(description: "Give your seat up on the subway with a smile.")
KindAct.create(description: "Make or buy them a small gift.")
